### PR TITLE
Add G Data blog post about Andromeda botnet

### PR DESCRIPTION
**Pull request by nyx0**

### CODE REVIEW

**Comment by mtmcgrew** [comment]
This is not a targeted or sophisticated attack at all, does it belong here?

**Comment by krmaxwell** [comment]
Personally, I don't think it should be in this particular repo (but that's not to say it's not important for hunting financially motivated attackers.

Also, when I hear "G DATA" all I can think is

image

**Comment by deadbits** [comment]
I'd have to agree with @krmaxwell and @mtmcgrew on, while this is an interesting botnet to see getting more public attention recently I don't think it would be classified as an advanced persistent threat. 

As far as I know, it is not state sponsored or politically motivated, or even motivated by direct corporate espionage; even though it is still very interesting none the less. Following the logic of adding this we'd have to start including things like Asprox or ZeroAccess.

**Comment by nyx0** [comment]
Ok I agree there are enough comments to close my PR :p

**Comment by mtmcgrew** [comment]
But Nyx, thanks for adding lots of other reports for this repo. Much appreciated!


On Mar 19, 2015, at 6:58 AM, Nyx <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #96<https://github.com/kbandla/APTnotes/pull/96>.

**Pull request closed without merging**
