### PR TITLE
Re-order the dates in reverse chronological order

### PR DESCRIPTION
**Pull request by nyx0**

### CODE REVIEW

**Comment by krmaxwell** [comment]
but still see #110 :+1:

**Comment by krmaxwell** [comment]
This reverses the years but not the dates. Think you could do that as well?

**Comment by nyx0** [comment]
At the beginning I reversed the date order but I found it weird to see entries like that. But if you want I can do this.

**Comment by krmaxwell** [comment]
Hrm. Curious what others think about that?

**Comment by nyx0** [comment]
@krmaxwell check the last commit abe5f434918e298baf12b85c7c91a03d82bfdc49

**Comment by krmaxwell** [comment]
@kbandla any thoughts? I like it.

**Comment by nyx0** [comment]
@kbandla Do you like this reordering?

**Comment by kbandla** [comment]
:+1: Looks good!

**Pull request merged**
