### PR TITLE
Update

### PR DESCRIPTION
**Pull request by nyx0**
Add Targeted Cyberattacks Logbook
Fix dates and urls

### CODE REVIEW

**Comment by nyx0** [comment]
Related to #67

**Comment by krmaxwell** [comment]
Really good catch on the URL fix. Ashamed I missed it!

For the Kaspersky site - I kind of wonder if we shouldn't call it out separately somehow, rather than as just another report. Thoughts?

**Comment by nyx0** [comment]
@krmaxwell Arf I don't know I added it here waiting to find a better place. But if we add it with other reports, what date do we put? Because it's frequently updated.

**Comment by krmaxwell** [comment]
Maybe @kbandla has some thoughts?

**Comment by nyx0** [comment]
@kbandla any update?

**Comment by krmaxwell** [comment]
Eh. Good enough for now. We can revisit if needed later.

**Pull request merged**
