### PR TITLE
Add repo links for each document to README.md 

### PR DESCRIPTION
**Pull request by ascendr**
Mapped the doc title to the document in the repo; created a "Repo" link to quickly jump to it. Saves some guesswork

### CODE REVIEW

**Comment by deadbits** [comment]
I think that having the reports broken up by year is pretty easy to navigate as-is, and with the README file showing links to the direct reports and the associated year there should not be much confusion as to which folder to visit to find the desired report. A simple Ctrl+F should be able to direct the user to the right report within each folder.

Also, adding the links to the README will only be functional within GitHub itself. If someone cloned this repo and was reading the file in $text-editor-of-choice, the links to each subfolder wouldn't serve a purpose if I'm not mistaken?

**Comment by ascendr** [comment]
I needed to map each entry in the README.md to an actual file for a project I am working on ( a web based keyword searchable pdf repo).  There was actually quite a bit of missing / misfiled reports and ambiguity.  I figured I would share back the result of my efforts.

**Comment by krmaxwell** [comment]
The place where this probably makes more sense is for reports where the original source is no longer online (404s). We have a few of those still and it's probably worth figuring out what to do with those.

**Comment by krmaxwell** [comment]
I've been noodling on this some more and liking the original idea. One of the issues I have is that, when going into a directory with the reports for a given year, I have to figure out which file is the actual report. One way, of course, is the link in the README file as proposed. We could also rename the actual PDFs to include the date as listed in the README, or (ugh) maintain some additional mapping. I mention the last only for completeness, we shouldn't do that as it's a particularly ugly way to go.

**Comment by beast-fighter** [comment]
This is going to be changed with the new table I created - will be adding to repo tomorrow (if time allows)

**Comment by beast-fighter** [comment]
folders and README are only going to be left in place for historical going forward - URL problem is resolved with now implemented box usage

**Pull request closed without merging**
