### PR TITLE
updating

### LINKED ISSUE #235: Uncovering the Seven Pointed Dagger
Jan 11, 2016
https://asert.arbornetworks.com/wp-content/uploads/2016/01/ASERT-Threat-Intelligence-Brief-Uncovering-the-Seven-Pointed-Dagger.pdf

### PR DESCRIPTION
**Pull request by irenad**
2016 - clearsky - dusty sky /clsoe #232 
2015 - checkpoint - rocket kitten
2015 - symantec - cadelspy - remexi
2016 - Arbor networks - seven edged dagger /close #235

### CODE REVIEW

**Comment by irenad** [comment]
closes issue #232

**Comment by beast-fighter** [comment]
http://blog.checkpoint.com/wp-content/uploads/2015/11/rocket-kitten-report.pdf (Rocket Kitten | PDF)

http://www.symantec.com/connect/blogs/iran-based-attackers-use-back-door-threats-spy-middle-eastern-targets (Iran Based Attackers Use Backdoor Threats | Blog)

other two were added recently

**Comment by beast-fighter** [comment]
Rocket Kitten added in 9de4bd1

**Comment by beast-fighter** [comment]
Symantec blog added in 246ac79

**Pull request closed without merging**
