### PR TITLE
Add report on the Kraken from G DATA

### PR DESCRIPTION
**Pull request by nyx0**

### CODE REVIEW

**Comment by krmaxwell** [comment]
Do you have the PDF export?

**Comment by nyx0** [comment]
Arf I'm on it sorry

**Comment by nyx0** [comment]
@krmaxwell Could you take a look at the pdf to know if it's ok for you? Thank you

**Comment by nyx0** [comment]
@krmaxwell Is something missing to merge the PR?

**Comment by krmaxwell** [comment]
Can you fix the merge conflict? Otherwise I guess it looks good!

**Pull request closed without merging**
